In [9]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

from sklearn.metrics import accuracy_score,confusion_matrix, classification_report

In [3]:
#DEFINE DATA
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([1,0,0,1])

In [5]:
#BUILD MODEL
model=Sequential([
    Dense(4,input_dim=2,activation='relu'),
    Dense(1,activation='sigmoid')
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [6]:
#COMPILE MODEL
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

#TRAIN MODEL
history = model.fit(X,y,
                    epochs=5,
                    verbose=1)


Epoch 1/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.5000 - loss: 0.6623
Epoch 2/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.7500 - loss: 0.6616
Epoch 3/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.7500 - loss: 0.6609
Epoch 4/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.7500 - loss: 0.6601
Epoch 5/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.7500 - loss: 0.6594


In [17]:
#PRINT WEIGHTS AND BIASES
for i,layer in enumerate(model.layers):
  w,b = layer.get_weights()
  print("Layer",i,layer.name)
  print("weights:\n",w)
  print("biases:\n",b)

Layer 0 dense_1
weights:
 [[ 0.23578554  0.6496751   0.45479     0.41443074]
 [-0.23311384  0.7375156  -0.9077289  -0.13332185]]
biases:
 [-0.00499291 -0.00028311  0.00199648  0.00473542]
Layer 1 dense_2
weights:
 [[-0.4333232 ]
 [-0.39661282]
 [-0.7981182 ]
 [ 1.0137749 ]]
biases:
 [0.00499297]


In [11]:
#VISUALIZE
#EVALUATE
(loss,accuracy) = model.evaluate(X,y)
print("loss:",loss)
print("acc:",accuracy)




1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.7500 - loss: 0.6588
loss: 0.6588473320007324
acc: 0.75


In [15]:
#PREDICT ONE INSTANCE
sample=np.array([[0,1]])
pred = model.predict(sample)
print("predicted:",pred.round())
print("Actual: 0")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
predicted: [[0.]]
Actual: 0
